### ISSUE TITLE
Unable to Publish Custom API

### ISSUE THREAD

**Issue by manishratan** [olisterr/Generic-Attachment-Template#1]
Hello Team,

Tried to publish Custom API of "Warehouse Activity Header" Table but even after deploying the extension, we are unable to find out the API. Attached is the existing list of API.
![Table Link](https://user-images.githubusercontent.com/45168210/74911064-df75ae80-53e1-11ea-99d7-9b1947dc15bb.png)

Have followed the steps given on below mentioned link:
https://saurav-nav.blogspot.com/2018/04/microsoft-dynamics-nav-2018-api-part-4.html
https://saurav-nav.blogspot.com/2019/09/api-part-5-add-custom-api-in-list.html

Requirement :
 Need to create a Power App using this Custom API( "Warehouse Activity Header").

Platform : Dynamics 365 Business Central
Version : 15.0.39461.40778 (On Cloud)

**Comment by olisterr** [comment]
Hi Manish,
You will not be able to get Custom Business Central APIs in PowerApps.You will need to create an ODATA connector using HTTP Connector in PowerApps.

You can refer 
https://www.olisterr.tech/2019/07/how-to-use-rss-feeds-ms-flow-microsoft.html
https://www.olisterr.tech/2019/09/understanding-apis-in-business-central.html

Also, this is a different GitHub Repository with regards to your context. Thus I will be closing this issue.
